name: Diff CCD definition

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17

  buildBranch:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
        with:
          path: build/branch
          repository: hmcts/nfdiv-case-api # TODO remove
          ref: nfdiv-date-picker # TODO remove
      - name: Build
        run: ./gradlew generateCCDConfig
        working-directory: build/branch
      - uses: actions/upload-artifact@v3
        with:
          name: branch
          path: build/branch/build/definitions/NFD

  buildMaster:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          path: build/master
          repository: hmcts/nfdiv-case-api # TODO remove
      - name: Build
        run: ./gradlew generateCCDConfig
        working-directory: build/master
      - uses: actions/upload-artifact@v3
        with:
          name: master
          path: build/master/build/definitions/NFD

  report:
    runs-on: ubuntu-latest
    needs: [buildBranch, buildMaster]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: branch
          path: build/branch
      - uses: actions/download-artifact@v3
        with:
          name: master
          path: build/master
      - name: Generate report
        id: ccd-diff
        run: echo "::set-output name=content::"$(npm --silent start build/master build/branch)""
      - name: Display
        run: |
          echo "Report output: "${{ steps.ccd-diff.outputs.content }}""
      - name: Add report
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: "# CCD diff report "${{ steps.ccd-diff.outputs.content }}""
          comment_includes: CCD diff report
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: "# CCD diff report ${{ steps.ccd-diff.outputs.content }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
