name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set node version and build
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat ./package.json
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
      - run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
